
   
runtime: nodejs16
env: standard
entrypoint: npm run next-api
# runtime: custom
# env: flex
instance_class: F1

default_expiration: '0d 0h'

automatic_scaling:
    target_cpu_utilization: 0.70
    min_instances: 1
    max_instances: 10
    max_concurrent_requests: 80
    max_idle_instances: 1
    min_idle_instances: 1
    min_pending_latency: 30ms
    max_pending_latency: automatic

# Force https for all requests - but doesn't seem to work?
handlers:
    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto

# # memory_gb: 0.6

env_variables:
    USE_ENV: prod
    NODE_ENV: prod
    GCLOUD_PROJECT_DAO: 'cryptopool-backend'