export enum PbPayCoins {
  ADA = 'ADA',
  BTC = 'BTC',
  ETH = 'ETH',
  BCH = 'BCH',
  BNB = 'BNB',
  DASH = 'DASH',
  DOGE = 'DOGE',
  LTC = 'LTC',
  MATIC = 'MATIC_POLYGON_MUMBAI',
  SOL = 'SOL',
  TRX = 'TRX',
  USDC = 'USDC',
  USDT = 'USDT_ERC20',
  XRP = 'XRP',
}
