const imagesUrl = '/image/';
const iconsUrl = '/icons/';

export const imagesPng = {
  loginPageBanner: `${imagesUrl}loginPage-banner.png`,
  signupPageBanner: `${imagesUrl}singupPage-banner.png`,
  inviteFriend: `${imagesUrl}inviteFriend.png`,
};

export const imagesSvg = {
  mark: 'tickmark.svg',
  checkMail: 'checkMail.svg',
  filter: 'filter.svg',
  downIcon: 'down.svg',
  upIcon: 'up.svg',
  cryptoPoolLogo: `${iconsUrl}cryptoPool.svg`,
  smallChart: `${imagesUrl}smallChart.svg`,
  profilePhoto: `${imagesUrl}userImage.svg`,
  otherPaymentIcon: `${imagesUrl}otherPayments.svg`,
  cryptoCurrency: `${imagesUrl}cryptoCurrency.svg`,
  chart: `${imagesUrl}chart.png`,
  download: 'download.svg',
  arrowDropDown: 'arrowDropDown.svg',
  pdfIcon: 'pdfIcon.svg',
  bottomArrow: 'bottomArrow.svg',
  supportIcon: 'support.svg',
  questionIcon: 'question.svg',
  merchantIcon: 'merchant.svg',
  hiddenIcon: 'hidden.svg',
  successIcon: 'successProfile.svg',
  rejectIcon: 'reject.svg',
  rupeeIcon: 'rupi.svg',
  edit: 'edit.svg',
  income: 'sales.svg',
  sales: 'totalSales.svg',
  transaction: 'transactionSales.svg',
  customer: 'customerSales.svg',
  walletIcon: 'walletIcon.svg',
  arrow: 'arrow.svg',
  rupeeConversion: 'rupeeConversion.svg',
  dollarConversion: 'dollarConversion.svg',
  bitcoin: 'bitcoin.svg',
  ethereum: 'ethereum.svg',
  creditCard: 'creditCard.svg',
  linkSettings: 'linkSettings.svg',
  invoiceIcon: 'invoiceIcon.svg',
  qrIcon: 'qrIcon.svg',
  goTo: 'goTo.svg',
  generatorApi: 'generatorApi.svg',
  invoiceLink: 'invoiceLink.svg',
  generateQR: 'generateQr.svg',
  shareLink: 'shareLink.svg',
  success: 'success.svg',
  gradientLine: 'gradientLine.svg',
  nextIcon: 'nextIcon.svg',
  close: 'close.svg',
  bankIcon: 'bankIcon.svg',
  bitcoinIcon: 'bitcoinIcon.svg',
  dollarIcon: 'dollarIcon.svg',
  warning: 'warning.svg',
  bitcoinCash: 'bitcoinCash.svg',
  facebook: 'facebook.svg',
  twitter: 'twitter.svg',
  telegram: 'telegram.svg',
  whatsapp: 'whatsapp.svg',
  copy: 'copy.svg',
  checkIcon: 'check.svg',
  arrowRightFirst: 'arrowRightFirst.svg',
  arrowRightSecond: 'arrowRightSecond.svg',
  crossIcon: 'cross.svg',
  closeIcon: 'close.svg',
  pending: 'wrong.svg',
  fail: 'fail.svg',
  done: 'done.svg',
  url: 'link.svg',
  search: 'search.svg',
  userCard: 'cardUserIcon.svg',
  bankCard: 'cardBankIcon.svg',
  closeNotification: 'closeNotification.svg',
  congrats: 'congrats.svg',
  clappingHands: 'clappingHands.svg',
  modalLogo: 'modalLogo.svg',
  goBack: 'goBack.svg',
  qrCode: 'qrCode.svg',
  wallet: 'wallet.svg',
  timer: 'timer.svg',
  metamask: 'metamask.svg',
};
